### ISSUE TITLE
Arity errors in calculateSampleByComponentMatrixDrews

### ISSUE THREAD

**Issue by jbedo** [markowetzlab/CINSignatureQuantification#17] opened 2023-03-09 23:54 UTC
I'm encountering the following error on some samples:
```
> Error in rowSums(postDatUnscaled) :
> 'x' must be an array of at least two dimensions
> Calls: quantifyCNSignatures ... calculateSampleByComponentMatrixDrews -> lapply -> FUN -> data.frame -> rowSums
````
This was thrown after calling `quantifyCINSignatures` and an inspection of the input doesn't reveal any obvious issues.

**Comment by Phil9S** [comment] 2023-03-10 09:16
Hello,

Thanks for reporting this. I could use some more information if possible.

- Can you run the example data provided? `data("TCGA_478_Samples_SNP6_GOLD")`
- What is your input (a file header and some example lines would be beneficial)?
- How many samples are you using in your input file? There have been issues with inputs containing only one sample previously.

If you are able to minimally reproduce this error and send some files for me to test that would be ideal.

**Comment by jbedo** [comment] 2023-03-10 11:21
The example data works fine, as do some other samples running through
exactly the same pipeline. Input (redacted sample names) is like this:
```
chromosome	start	end	segVal	sample
1	840001	870000	2.95466	d15bc1f1282fa266d821cd406579308d3720817c4
1	870001	900000	2.95466	d15bc1f1282fa266d821cd406579308d3720817c4
1	900001	930000	2.95466	d15bc1f1282fa266d821cd406579308d3720817c4
```
There is only one sample so good to know more samples might be more
reliable. I'll try and derive a minimal example.

**Comment by Phil9S** [comment] 2023-03-10 12:04
I don't think that its the issue but it looks like you are using a binned input (every segment is a fixed width of 30kb), where these should be collapsed into a single segment (1:840001-930000 in the example). Otherwise samples will have 80,000+ segments and the signatures will be computed incorrectly. I will implement a check for this in the future.

Please update me if you resolve this or can provide an example file for me to test internally.

**Comment by jbedo** [comment] 2023-03-12 06:17
Thanks, good to know. Here's a minimal example that triggers the error
for me:
```
chromosome	start	end	segVal	sample
1	97980001	98010000	2.95466	sample
1	189750001	189780000	2.40493	sample
3	157230001	157260000	2.83234	sample
4	155100001	155130000	2.12431	sample
5	160740001	160770000	2.98554	sample
6	112710001	112740000	2.93019	sample
7	146010001	146040000	2.13612	sample
8	120570001	120600000	2.59906	sample
9	134160001	134190000	2.12431	sample
10	130530001	130560000	2.65552	sample
11	130800001	130830000	2.85599	sample
12	127020001	127050000	2.64633	sample
13	77280001	77310000	1.60324	sample
14	45780001	45810000	2.51401	sample
15	92640001	92670000	2.18706	sample
16	72630001	72660000	1.85317	sample
17	53790001	53820000	2.73965	sample
19	33270001	33300000	2.18554	sample
20	43380001	43410000	2.99176	sample
22	30780001	30810000	2.70193	sample
```

**Comment by Phil9S** [comment] 2023-03-20 18:54
Thanks for your patience. The error is occurring during feature fitting because the profile contains zero oscillating chains, one of the features we capture. I have fixed this bug in both CN signature methods though, this should only be a problem in copy number profiles in which there are essentially no segment changes, in which case copy number signatures cannot be computed either way.

I have opened a pull request #18 which fixes this and will be incorporated into a new release v1.1.2.

**N.B**

The bigger concern is that the data you provided is not a complete copy number profile. Here is your data plotted as a segmented profile. I would suggest reviewing your data before using copy number signatures given your input is currently inappropriate (under the assumption this is what all your data looks like, I could be wrong).

![image](https://user-images.githubusercontent.com/23719663/226427300-d1347cb8-6d9b-4d5e-ae38-602251332287.png)

You can load the data using the `createCNQuant()` function and plot the profiles using the `plotSegments()` function from this package if you wish to quickly visualise the rest of your samples.

**Closed as completed** 2023-03-20 18:55 UTC

**Comment by jbedo** [comment] 2023-03-20 23:14
Thanks for the fix. Just to be clear, that example was constructed to help you debug.
